apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
  labels:
    app: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
        - name: ssh
          image: corbinu/ssh-server
          volumeMounts:
            - name: ssh-key
              mountPath: /root/ssh-key
            - name: ceph-nfs
              mountPath: /pv/ceph-nfs
          ports: 
            - containerPort: 22
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cat /root/ssh-key/id_rsa.pub >> /root/.ssh/authorized_keys"]
      volumes:
        - name: ssh-key
          secret:
            secretName: my-ssh-public-key
            defaultMode: 256
        - name: ceph-nfs
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: home
              clusterNamespace: rook-ceph

---

apiVersion: v1
kind: Service
metadata:
  name: ssh
  labels:
    app: ssh
spec:
  type: NodePort
  ports:
  - name: "22"
    port: 22
    # nodePort: ???  # dynamically set by k8 - you can set this value after assignment
  selector:
    app: ssh
status:
  loadBalancer: {}
